# Generated by Django 3.2.6 on 2021-08-23 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_bookmarked',
            field=models.BooleanField(default=False),
        ),
    ]
