# Generated by Django 3.2.6 on 2021-11-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['slno']},
        ),
        migrations.RenameField(
            model_name='question',
            old_name='corresponding_page_no',
            new_name='page_no',
        ),
        migrations.AddField(
            model_name='chapter',
            name='slno',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=200),
        ),
    ]
