# Generated by Django 3.2.6 on 2021-11-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_auto_20211122_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='rule',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
