# Generated by Django 3.2.6 on 2021-11-22 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_question_rule'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageComplition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.chapter')),
            ],
        ),
    ]
