# Generated by Django 3.2.9 on 2021-11-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0004_pagecomplition'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='scroll_height',
            field=models.FloatField(default=0.0),
        ),
    ]
